address:
  complete:
    url: http://localhost:8081/api/v1/address-complete

google:
  api-key: ${GOOGLE_API_KEY}
  address:
    base-url: https://addressvalidation.googleapis.com

spring:
  config:
    import: optional:classpath:application-local.yml
